
define: &img_shape [1024, 1024]
define: &scales 1

logger:
  project: StochasticAttention-DiabeticRetinopathy

data:
  data_dir: /home/tmp/clpla/data/eyepacs/
  img_size: *img_shape
  batch_size: 6
  valid_size: 4000
  num_workers: 4
  superpixels_min_nb: 2048
  superpixels_scales: *scales
  superpixels_filter_black: True
  superpixels_num_threads: 1
  superpixels_compactness: 1
  use_superpixels: True

model:
  inter_dim: 256
  arch: dyn_vit
  resample_every_n_blocks: 4
  number_of_prototypes: 16
  img_size: *img_shape
  num_classes: 5
  global_pool: 'avg'
  
training:
  lr: 0.001
  as_regression: True
  pct_start: 0.1
  optimizer:
    betas: [.9, .999]
    weight_decay: 0.00003
    fused: fused

trainer:
  accumulate_grad_batches: 48
  strategy: auto
  accelerator: auto
  deterministic: False
  devices: auto
  max_epochs: 1000
  precision: 32
  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 2
