
define: &img_shape [1024, 1024]

logger:
  project: Protoype-ViT initialization

data:
  data_dir: /home/tmp/clpla/data/Maples-DR/
  img_size: *img_shape
  batch_size: 4
  valid_size: 0.2
  num_workers: 8
  superpixels_nb: 4096
  superpixels_filter_black: True
  superpixels_num_threads: 0

model:
  features_extractor: resnet34
  n_protos: 12
  
training:
  lr: 0.001
  weight_decay: 0.

trainer:
  accumulate_grad_batches: 1
  strategy: ddp_find_unused_parameters_true
  accelerator: gpu
  deterministic: False
  max_epochs: 100
  precision: 32
  gradient_clip_val: 1.0
  check_val_every_n_epoch: 10
  num_sanity_val_steps: 2
  fast_dev_run: False
