
define: &img_shape [1024, 1024]
define: &scales 1

logger:
  project: StochasticAttention-DiabeticRetinopathy

data:
  data_dir: /home/clement/Documents/data/DDR/DDR-dataset/DR_grading/
  img_size: *img_shape
  batch_size: 6
  valid_size: 4000
  num_workers: 7
  superpixels_max_nb: 8192
  superpixels_min_nb: 1024
  superpixels_scales: *scales
  superpixels_filter_black: True
  superpixels_num_threads: 1

model:
  first_embedding_dim: 32
  arch: svt_16_large
  img_size: *img_shape
  num_classes: 5
  max_tokens: 4096
  scales: *scales
  projection_stride: 1
  pretrained: True
  drop_path: 0.2
  global_pool: False
  single_cls_token: True
  padding: 0
  detach_input: False
  
training:
  lr: 0.0001
  as_regression: True
  optimizer:
    betas: [.9, .999]
    weight_decay: 0.0005

trainer:
  accumulate_grad_batches: 4
  strategy: auto
  accelerator: auto
  deterministic: False
  devices: 3
  max_epochs: 100
  precision: 32
  gradient_clip_val: 1.0
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 2
  fast_dev_run: False
